version: '3'

services:
  nginx_php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Можете изменить порт по желанию
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/:/usr/share/nginx/html


  pma:
    image: phpmyadmin
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      - PMA_ARBITRARY=1

  mysql_db.main:
    container_name: mysql_db.main
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - './volumes/db/mysql/main:/var/lib/mysql'
    env_file:
      - .env
