version: '3'

services:
  apache_webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:81"  # Можете изменить порт по желанию
    volumes:
      - ./apache-config/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./html/:/var/www/html
