CREATE TABLE `pv111`.`users`
(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
    `email` VARCHAR(64) NOT NULL ,
    `password` VARCHAR(256) NOT NULL ,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` DATETIME on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY (`id`), UNIQUE (`email`)
) ENGINE = InnoDB;
