version: '3'
services:

  # Мой первый веб сервер
  webserver:
    # Из какой папки собрать контейнер
    # В этой папке должен быть Dockerfile
    build: ./WebServer
    # Какую внешню папку смонтировать внутри контейнера
    volumes:
      - ./WebServer:/usr/src/app
    # Какую команду выполнить в момент запуска контейнера
    command: sh -c " npm install && npm start "

    container_name: webserver
    environment:
      - SERVER_NAME=webserver
    ports:
      - "80:80"


  # База данных
  db.postgresql:
    container_name: db.postgresql
    # Имя образа - на основе которого будет создан контейнер
    image: postgres:16
    # Переменные окружения (логин, пароль и тд, для создания контейнера)
    # https://hub.docker.com/_/postgres - описываются в документации
    environment:
      - SOME_VAR=some_value
    # Переменные окружения принято располагать в отдельном фале
    # для соблюдения норм безопасности
    env_file:
      - .env
    # Разрешить доступ с родительской машины
    ports:
      - "5432:5432"
    # Укажем папку для хранения базы данных в главной машине
    volumes:
      - ./volumes/db.postgresql:/var/lib/postgresql


  # inMemory DB - используется для кеширвоания и обмена сообщениями
  db.redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./volumes/redis:/data

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - .env


