version: '3'

services:
  roadrunner_webserver_php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Можете изменить порт по желанию
      - "6001:6001"  # Можете изменить порт по желанию
    volumes:
      - ./roadrunner-config/.rr.yaml:/etc/.rr.yaml
      - ./html:/var/www/html
