openapi: 3.0.0
info:
  title: 'My First Laravel'
  description: "## Introduction\n\n API documentation for Pandora - REST API starter kit powered by Laravel, OpenAPI, Sanctum.\n\n- [GitHub](https://github.com/arifszn/pandora)\n- [MIT License](https://github.com/arifszn/pandora/blob/main/LICENSE)"
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
    description: 'Local API server'
  -
    url: 'http://api.admin.user.com'
    description: 'Global API server'
paths:
  /api/photo:
    post:
      tags:
        - photo
      summary: 'Create new photo'
      description: "Store a newly created resource in storage.\nЕсли я доку пропишу здесь ???"
      operationId: photo.store
      responses:
        '201':
          description: Created
        '422':
          description: 'Unprocessable entity'
components:
  schemas:
    ValidationError:
      properties:
        message:
          type: string
          example: 'The given data was invalid.'
        errors:
          properties:
            'key 1':
              type: array
              items:
                type: string
                example: 'Error message 1'
            'key 2':
              type: array
              items:
                type: string
                example: 'Error message 2'
          type: object
      type: object
  securitySchemes:
    BearerToken:
      type: http
      bearerFormat: JWT
      scheme: bearer
tags:
  -
    name: auth
    description: 'User authentication'
  -
    name: adminAuth
    description: 'Admin authentication'
  -
    name: profile
    description: 'User profile'
  -
    name: photo
    description: Photo
