version: '3'
services:

  # Для определения кому обрабатывать тот или иной запрос мне нужен посредник
  # он по части маршрута определит - какой из контейнеров должен обработать запрос
  # в идеале - он передаст запрос самому свободному контейнеру (но это уже работа devOps)
  api.gatway:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  # Этот контейнер будет работать с авторизацией и аутентификацией пользователя
  api.auth:
    build: ./backend/auth
    volumes:
      - ./backend/auth/src:/usr/src/app
    command: sh -c " npm install && npm start "
    container_name: api.auth
    env_file:
      - .env

  # Этот контейнер должен узнавать - кто к нему пришел
  api.posts:
    build: ./backend/posts
    volumes:
      - ./backend/posts/src:/usr/src/app
    command: sh -c " npm install && npm start "
    container_name: api.posts
    env_file:
      - .env

