version: '3'

services:
  nginx_webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Можете изменить порт по желанию
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
      - ./html/:/usr/share/nginx/html
